version: "3.5"

networks:
    chess:
        external: false

services:
    server:
        build: .
        container_name: chess_server
        networks:
            - chess
        volumes:
            - /var/chess:/data
        ports:
            - "${HTTP_PORT}:80"
        environment:
            - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
            - ADMIN_KEY=${ADMIN_KEY}
